### ISSUE TITLE
EPIC: Create, update and view incident reports

### ISSUE THREAD

**Issue by xivind** [xivind/velo-supervisor-2000#51]
Suggestion by TR. User story: 
```
As a user
I want to be able to flag components that are broken
So I easily see what must be immediately fixed
```
**Misc tasks**
- [x] Fix javascript warning message (probably something about how handlers are added to buttons)
- [x] Check exactly what is written to the database in different use cases, particularly NULL values
- [x] Test on all pages
- [x] Rename certain field to included incident_, so they are not mixed up with similar field in workplan (requires some refactoring)

**Comment by xivind** [comment]
Placeholder added in menu, backend and frontend missing

**Comment by xivind** [comment]
@thomiz  finally, the incident reporting is in place! I need to do a bit more testing before pushing it to staging, but if you like you can test already now from dev. In that case, do only test on test data. This code is not production ready. Database migration is required, and that tool has also been updated as well. If any case, I will let you know when the code is better tested and available in staging. But I think we are finally near the finish here, and the workplan will be much faster to implement.

**Comment by xivind** [comment]
Tested and ready for review, can be pushed to staging.  Test the database migration tool first and re-enable Strava sync #250

**Comment by xivind** [comment]
@thomiz the feature you requested, incident reports, is now available in staging. In staging now is also an improved version of the database migration tool, addressing the bug you filed in #250 Your usual rigorous testing would be very welcome! Please let me know how it goes, and if it looks ok, I will push this to main and get started on workplans.

**Comment by xivind** [comment]
@thomiz fixed the js-problem, ready for testing! Staging is up to date.

**Comment by thomiz** [comment]
Have been testing this feature. Great work. However I find myself entering the same information everywhere. Services, workplan and incident: look at comment https://github.com/xivind/velo-supervisor-2000/issues/242#issuecomment-2920527581

Because what I am doing is trying to fix an issue (recorded as an incident). I set up a workplan to evaluate and amend the problem, and this requires services of several components on the bike. In the end I have entered the same information three times; in the incident (how i worked on fixing it), in the work plan (what I did to complete the plan) and in the services of each compontents. This is getting hard work!

**Comment by xivind** [comment]
Ha ha @thomiz I FULLY support the notion to relieve the mechanics administrative burden. I understand the use case you are describing and will look into this. I will follow up on this request in a separate ticket #282

**Comment by xivind** [comment]
This epic is pushed to master and can be closed. Feature request for better integration between incidents, workplans and service will be followed up in #282
